// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.21.2
// source: msg.s3.proto

package pkt

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CopyObjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucketid   *CopyObjectResp_BucketId  `protobuf:"group,1,opt,name=BucketId,json=bucketid" json:"bucketid,omitempty"`
	BucketName *string                   `protobuf:"bytes,2,opt,name=bucketName" json:"bucketName,omitempty"`
	FileName   *string                   `protobuf:"bytes,3,opt,name=fileName" json:"fileName,omitempty"`
	Meta       []byte                    `protobuf:"bytes,4,opt,name=meta" json:"meta,omitempty"`
	Versionid  *CopyObjectResp_VersionId `protobuf:"group,5,opt,name=VersionId,json=versionid" json:"versionid,omitempty"`
	Fileid     *CopyObjectResp_FileId    `protobuf:"group,6,opt,name=FileId,json=fileid" json:"fileid,omitempty"`
}

func (x *CopyObjectResp) Reset() {
	*x = CopyObjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectResp) ProtoMessage() {}

func (x *CopyObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectResp.ProtoReflect.Descriptor instead.
func (*CopyObjectResp) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{0}
}

func (x *CopyObjectResp) GetBucketid() *CopyObjectResp_BucketId {
	if x != nil {
		return x.Bucketid
	}
	return nil
}

func (x *CopyObjectResp) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

func (x *CopyObjectResp) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *CopyObjectResp) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CopyObjectResp) GetVersionid() *CopyObjectResp_VersionId {
	if x != nil {
		return x.Versionid
	}
	return nil
}

func (x *CopyObjectResp) GetFileid() *CopyObjectResp_FileId {
	if x != nil {
		return x.Fileid
	}
	return nil
}

type GetBucketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketName *string `protobuf:"bytes,1,opt,name=bucketName" json:"bucketName,omitempty"`
	Meta       []byte  `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (x *GetBucketResp) Reset() {
	*x = GetBucketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketResp) ProtoMessage() {}

func (x *GetBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketResp.ProtoReflect.Descriptor instead.
func (*GetBucketResp) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{1}
}

func (x *GetBucketResp) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

func (x *GetBucketResp) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetObjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   *string           `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	Id         *GetObjectResp_Id `protobuf:"group,2,opt,name=Id,json=id" json:"id,omitempty"`
	Meta       []byte            `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	BucketName *string           `protobuf:"bytes,4,opt,name=bucketName" json:"bucketName,omitempty"`
}

func (x *GetObjectResp) Reset() {
	*x = GetObjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResp) ProtoMessage() {}

func (x *GetObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResp.ProtoReflect.Descriptor instead.
func (*GetObjectResp) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectResp) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *GetObjectResp) GetId() *GetObjectResp_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetObjectResp) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetObjectResp) GetBucketName() string {
	if x != nil && x.BucketName != nil {
		return *x.BucketName
	}
	return ""
}

type ListBucketResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buckets *ListBucketResp_Buckets `protobuf:"group,1,opt,name=Buckets,json=buckets" json:"buckets,omitempty"`
}

func (x *ListBucketResp) Reset() {
	*x = ListBucketResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketResp) ProtoMessage() {}

func (x *ListBucketResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketResp.ProtoReflect.Descriptor instead.
func (*ListBucketResp) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{3}
}

func (x *ListBucketResp) GetBuckets() *ListBucketResp_Buckets {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type ListObjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filemetalist []*ListObjectResp_FileMetaList `protobuf:"group,1,rep,name=FileMetaList,json=filemetalist" json:"filemetalist,omitempty"`
}

func (x *ListObjectResp) Reset() {
	*x = ListObjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectResp) ProtoMessage() {}

func (x *ListObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectResp.ProtoReflect.Descriptor instead.
func (*ListObjectResp) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{4}
}

func (x *ListObjectResp) GetFilemetalist() []*ListObjectResp_FileMetaList {
	if x != nil {
		return x.Filemetalist
	}
	return nil
}

type ListObjectRespV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Lastline *bool  `protobuf:"varint,2,opt,name=lastline" json:"lastline,omitempty"`
}

func (x *ListObjectRespV2) Reset() {
	*x = ListObjectRespV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectRespV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectRespV2) ProtoMessage() {}

func (x *ListObjectRespV2) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectRespV2.ProtoReflect.Descriptor instead.
func (*ListObjectRespV2) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{5}
}

func (x *ListObjectRespV2) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListObjectRespV2) GetLastline() bool {
	if x != nil && x.Lastline != nil {
		return *x.Lastline
	}
	return false
}

type StringMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string          `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Vals []*StringMap_Vals `protobuf:"group,2,rep,name=Vals,json=vals" json:"vals,omitempty"`
}

func (x *StringMap) Reset() {
	*x = StringMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMap) ProtoMessage() {}

func (x *StringMap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMap.ProtoReflect.Descriptor instead.
func (*StringMap) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{6}
}

func (x *StringMap) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *StringMap) GetVals() []*StringMap_Vals {
	if x != nil {
		return x.Vals
	}
	return nil
}

type CopyObjectResp_BucketId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *CopyObjectResp_BucketId) Reset() {
	*x = CopyObjectResp_BucketId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyObjectResp_BucketId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectResp_BucketId) ProtoMessage() {}

func (x *CopyObjectResp_BucketId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectResp_BucketId.ProtoReflect.Descriptor instead.
func (*CopyObjectResp_BucketId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CopyObjectResp_BucketId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CopyObjectResp_BucketId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *CopyObjectResp_BucketId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *CopyObjectResp_BucketId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type CopyObjectResp_VersionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *CopyObjectResp_VersionId) Reset() {
	*x = CopyObjectResp_VersionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyObjectResp_VersionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectResp_VersionId) ProtoMessage() {}

func (x *CopyObjectResp_VersionId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectResp_VersionId.ProtoReflect.Descriptor instead.
func (*CopyObjectResp_VersionId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CopyObjectResp_VersionId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CopyObjectResp_VersionId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *CopyObjectResp_VersionId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *CopyObjectResp_VersionId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type CopyObjectResp_FileId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *CopyObjectResp_FileId) Reset() {
	*x = CopyObjectResp_FileId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyObjectResp_FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectResp_FileId) ProtoMessage() {}

func (x *CopyObjectResp_FileId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectResp_FileId.ProtoReflect.Descriptor instead.
func (*CopyObjectResp_FileId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CopyObjectResp_FileId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CopyObjectResp_FileId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *CopyObjectResp_FileId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *CopyObjectResp_FileId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type GetObjectResp_Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *GetObjectResp_Id) Reset() {
	*x = GetObjectResp_Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjectResp_Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResp_Id) ProtoMessage() {}

func (x *GetObjectResp_Id) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResp_Id.ProtoReflect.Descriptor instead.
func (*GetObjectResp_Id) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetObjectResp_Id) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *GetObjectResp_Id) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *GetObjectResp_Id) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *GetObjectResp_Id) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type ListBucketResp_Buckets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count *uint32  `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Names []string `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
}

func (x *ListBucketResp_Buckets) Reset() {
	*x = ListBucketResp_Buckets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBucketResp_Buckets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketResp_Buckets) ProtoMessage() {}

func (x *ListBucketResp_Buckets) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketResp_Buckets.ProtoReflect.Descriptor instead.
func (*ListBucketResp_Buckets) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListBucketResp_Buckets) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *ListBucketResp_Buckets) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ListObjectResp_FileMetaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fileid    *ListObjectResp_FileMetaList_FileId    `protobuf:"group,1,opt,name=FileId,json=fileid" json:"fileid,omitempty"`
	Bucketid  *ListObjectResp_FileMetaList_BucketId  `protobuf:"group,2,opt,name=BucketId,json=bucketid" json:"bucketid,omitempty"`
	FileName  *string                                `protobuf:"bytes,3,opt,name=fileName" json:"fileName,omitempty"`
	Versionid *ListObjectResp_FileMetaList_VersionId `protobuf:"group,4,opt,name=VersionId,json=versionid" json:"versionid,omitempty"`
	Latest    *bool                                  `protobuf:"varint,5,opt,name=latest" json:"latest,omitempty"`
	Meta      []byte                                 `protobuf:"bytes,6,opt,name=meta" json:"meta,omitempty"`
	Acl       []byte                                 `protobuf:"bytes,7,opt,name=acl" json:"acl,omitempty"`
}

func (x *ListObjectResp_FileMetaList) Reset() {
	*x = ListObjectResp_FileMetaList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectResp_FileMetaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectResp_FileMetaList) ProtoMessage() {}

func (x *ListObjectResp_FileMetaList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectResp_FileMetaList.ProtoReflect.Descriptor instead.
func (*ListObjectResp_FileMetaList) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListObjectResp_FileMetaList) GetFileid() *ListObjectResp_FileMetaList_FileId {
	if x != nil {
		return x.Fileid
	}
	return nil
}

func (x *ListObjectResp_FileMetaList) GetBucketid() *ListObjectResp_FileMetaList_BucketId {
	if x != nil {
		return x.Bucketid
	}
	return nil
}

func (x *ListObjectResp_FileMetaList) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *ListObjectResp_FileMetaList) GetVersionid() *ListObjectResp_FileMetaList_VersionId {
	if x != nil {
		return x.Versionid
	}
	return nil
}

func (x *ListObjectResp_FileMetaList) GetLatest() bool {
	if x != nil && x.Latest != nil {
		return *x.Latest
	}
	return false
}

func (x *ListObjectResp_FileMetaList) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListObjectResp_FileMetaList) GetAcl() []byte {
	if x != nil {
		return x.Acl
	}
	return nil
}

type ListObjectResp_FileMetaList_FileId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *ListObjectResp_FileMetaList_FileId) Reset() {
	*x = ListObjectResp_FileMetaList_FileId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectResp_FileMetaList_FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectResp_FileMetaList_FileId) ProtoMessage() {}

func (x *ListObjectResp_FileMetaList_FileId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectResp_FileMetaList_FileId.ProtoReflect.Descriptor instead.
func (*ListObjectResp_FileMetaList_FileId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *ListObjectResp_FileMetaList_FileId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_FileId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_FileId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_FileId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type ListObjectResp_FileMetaList_BucketId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *ListObjectResp_FileMetaList_BucketId) Reset() {
	*x = ListObjectResp_FileMetaList_BucketId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectResp_FileMetaList_BucketId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectResp_FileMetaList_BucketId) ProtoMessage() {}

func (x *ListObjectResp_FileMetaList_BucketId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectResp_FileMetaList_BucketId.ProtoReflect.Descriptor instead.
func (*ListObjectResp_FileMetaList_BucketId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *ListObjectResp_FileMetaList_BucketId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_BucketId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_BucketId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_BucketId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type ListObjectResp_FileMetaList_VersionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *ListObjectResp_FileMetaList_VersionId) Reset() {
	*x = ListObjectResp_FileMetaList_VersionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListObjectResp_FileMetaList_VersionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectResp_FileMetaList_VersionId) ProtoMessage() {}

func (x *ListObjectResp_FileMetaList_VersionId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectResp_FileMetaList_VersionId.ProtoReflect.Descriptor instead.
func (*ListObjectResp_FileMetaList_VersionId) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{4, 0, 2}
}

func (x *ListObjectResp_FileMetaList_VersionId) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_VersionId) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_VersionId) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *ListObjectResp_FileMetaList_VersionId) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type StringMap_Vals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ival *int32  `protobuf:"varint,5,opt,name=ival" json:"ival,omitempty"`
	Lval *int64  `protobuf:"varint,6,opt,name=lval" json:"lval,omitempty"`
	Val  *string `protobuf:"bytes,9,opt,name=val" json:"val,omitempty"`
}

func (x *StringMap_Vals) Reset() {
	*x = StringMap_Vals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_s3_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMap_Vals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMap_Vals) ProtoMessage() {}

func (x *StringMap_Vals) ProtoReflect() protoreflect.Message {
	mi := &file_msg_s3_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMap_Vals.ProtoReflect.Descriptor instead.
func (*StringMap_Vals) Descriptor() ([]byte, []int) {
	return file_msg_s3_proto_rawDescGZIP(), []int{6, 0}
}

func (x *StringMap_Vals) GetIval() int32 {
	if x != nil && x.Ival != nil {
		return *x.Ival
	}
	return 0
}

func (x *StringMap_Vals) GetLval() int64 {
	if x != nil && x.Lval != nil {
		return *x.Lval
	}
	return 0
}

func (x *StringMap_Vals) GetVal() string {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return ""
}

var File_msg_s3_proto protoreflect.FileDescriptor

var file_msg_s3_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x2e, 0x73, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x70, 0x6b, 0x74, 0x22, 0xed, 0x05, 0x0a, 0x0e, 0x43, 0x6f, 0x70, 0x79, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x1c, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x43,
	0x6f, 0x70, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x3b, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0a, 0x32, 0x1d, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x32, 0x0a,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x1a, 0x2e,
	0x70, 0x6b, 0x74, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x69,
	0x64, 0x1a, 0x9e, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x11,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x1a, 0x9f, 0x01, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c,
	0x0a, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x1a, 0x9c, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a,
	0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0xa1, 0x02, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0a, 0x32, 0x15, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74,
	0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x98, 0x01, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x7e, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35,
	0x0a, 0x07, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0a, 0x32,
	0x1b, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x07, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a, 0x35, 0x0a, 0x07, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0xf5, 0x06, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x44, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x20, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x61, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x9c, 0x06, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x27, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x29, 0x2e, 0x70, 0x6b, 0x74, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x42, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x49, 0x64, 0x52, 0x08, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x2a, 0x2e,
	0x70, 0x6b, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x61,
	0x63, 0x6c, 0x1a, 0x9c, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x11, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x1a, 0x9e, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c, 0x0a, 0x11,
	0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x1a, 0x9f, 0x01, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2c,
	0x0a, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x56, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x6c, 0x61, 0x73, 0x74, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x76, 0x61,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x13, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x70, 0x2e, 0x56, 0x61, 0x6c, 0x73, 0x52, 0x04, 0x76,
	0x61, 0x6c, 0x73, 0x1a, 0x40, 0x0a, 0x04, 0x56, 0x61, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x69, 0x76, 0x61, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x76, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c,
	0x76, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x76, 0x61, 0x6c,
}

var (
	file_msg_s3_proto_rawDescOnce sync.Once
	file_msg_s3_proto_rawDescData = file_msg_s3_proto_rawDesc
)

func file_msg_s3_proto_rawDescGZIP() []byte {
	file_msg_s3_proto_rawDescOnce.Do(func() {
		file_msg_s3_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_s3_proto_rawDescData)
	})
	return file_msg_s3_proto_rawDescData
}

var file_msg_s3_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_msg_s3_proto_goTypes = []interface{}{
	(*CopyObjectResp)(nil),                        // 0: pkt.CopyObjectResp
	(*GetBucketResp)(nil),                         // 1: pkt.GetBucketResp
	(*GetObjectResp)(nil),                         // 2: pkt.GetObjectResp
	(*ListBucketResp)(nil),                        // 3: pkt.ListBucketResp
	(*ListObjectResp)(nil),                        // 4: pkt.ListObjectResp
	(*ListObjectRespV2)(nil),                      // 5: pkt.ListObjectRespV2
	(*StringMap)(nil),                             // 6: pkt.StringMap
	(*CopyObjectResp_BucketId)(nil),               // 7: pkt.CopyObjectResp.BucketId
	(*CopyObjectResp_VersionId)(nil),              // 8: pkt.CopyObjectResp.VersionId
	(*CopyObjectResp_FileId)(nil),                 // 9: pkt.CopyObjectResp.FileId
	(*GetObjectResp_Id)(nil),                      // 10: pkt.GetObjectResp.Id
	(*ListBucketResp_Buckets)(nil),                // 11: pkt.ListBucketResp.Buckets
	(*ListObjectResp_FileMetaList)(nil),           // 12: pkt.ListObjectResp.FileMetaList
	(*ListObjectResp_FileMetaList_FileId)(nil),    // 13: pkt.ListObjectResp.FileMetaList.FileId
	(*ListObjectResp_FileMetaList_BucketId)(nil),  // 14: pkt.ListObjectResp.FileMetaList.BucketId
	(*ListObjectResp_FileMetaList_VersionId)(nil), // 15: pkt.ListObjectResp.FileMetaList.VersionId
	(*StringMap_Vals)(nil),                        // 16: pkt.StringMap.Vals
}
var file_msg_s3_proto_depIdxs = []int32{
	7,  // 0: pkt.CopyObjectResp.bucketid:type_name -> pkt.CopyObjectResp.BucketId
	8,  // 1: pkt.CopyObjectResp.versionid:type_name -> pkt.CopyObjectResp.VersionId
	9,  // 2: pkt.CopyObjectResp.fileid:type_name -> pkt.CopyObjectResp.FileId
	10, // 3: pkt.GetObjectResp.id:type_name -> pkt.GetObjectResp.Id
	11, // 4: pkt.ListBucketResp.buckets:type_name -> pkt.ListBucketResp.Buckets
	12, // 5: pkt.ListObjectResp.filemetalist:type_name -> pkt.ListObjectResp.FileMetaList
	16, // 6: pkt.StringMap.vals:type_name -> pkt.StringMap.Vals
	13, // 7: pkt.ListObjectResp.FileMetaList.fileid:type_name -> pkt.ListObjectResp.FileMetaList.FileId
	14, // 8: pkt.ListObjectResp.FileMetaList.bucketid:type_name -> pkt.ListObjectResp.FileMetaList.BucketId
	15, // 9: pkt.ListObjectResp.FileMetaList.versionid:type_name -> pkt.ListObjectResp.FileMetaList.VersionId
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_msg_s3_proto_init() }
func file_msg_s3_proto_init() {
	if File_msg_s3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_s3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyObjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBucketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBucketResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectRespV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyObjectResp_BucketId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyObjectResp_VersionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyObjectResp_FileId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjectResp_Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBucketResp_Buckets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectResp_FileMetaList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectResp_FileMetaList_FileId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectResp_FileMetaList_BucketId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListObjectResp_FileMetaList_VersionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_s3_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMap_Vals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_s3_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_s3_proto_goTypes,
		DependencyIndexes: file_msg_s3_proto_depIdxs,
		MessageInfos:      file_msg_s3_proto_msgTypes,
	}.Build()
	File_msg_s3_proto = out.File
	file_msg_s3_proto_rawDesc = nil
	file_msg_s3_proto_goTypes = nil
	file_msg_s3_proto_depIdxs = nil
}
