// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.21.2
// source: msg.node.proto

package pkt

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetNodeCapacityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime  uint64 `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	RetryTimes uint32 `protobuf:"varint,2,opt,name=retryTimes,proto3" json:"retryTimes,omitempty"`
}

func (x *GetNodeCapacityReq) Reset() {
	*x = GetNodeCapacityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeCapacityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeCapacityReq) ProtoMessage() {}

func (x *GetNodeCapacityReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeCapacityReq.ProtoReflect.Descriptor instead.
func (*GetNodeCapacityReq) Descriptor() ([]byte, []int) {
	return file_msg_node_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodeCapacityReq) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetNodeCapacityReq) GetRetryTimes() uint32 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

type GetNodeCapacityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Writable bool   `protobuf:"varint,1,opt,name=writable,proto3" json:"writable,omitempty"`
	AllocId  string `protobuf:"bytes,2,opt,name=allocId,proto3" json:"allocId,omitempty"`
}

func (x *GetNodeCapacityResp) Reset() {
	*x = GetNodeCapacityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeCapacityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeCapacityResp) ProtoMessage() {}

func (x *GetNodeCapacityResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeCapacityResp.ProtoReflect.Descriptor instead.
func (*GetNodeCapacityResp) Descriptor() ([]byte, []int) {
	return file_msg_node_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeCapacityResp) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *GetNodeCapacityResp) GetAllocId() string {
	if x != nil {
		return x.AllocId
	}
	return ""
}

type ListDNIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextId string `protobuf:"bytes,1,opt,name=nextId,proto3" json:"nextId,omitempty"`
	Count  uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ListDNIReq) Reset() {
	*x = ListDNIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDNIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDNIReq) ProtoMessage() {}

func (x *ListDNIReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDNIReq.ProtoReflect.Descriptor instead.
func (*ListDNIReq) Descriptor() ([]byte, []int) {
	return file_msg_node_proto_rawDescGZIP(), []int{2}
}

func (x *ListDNIReq) GetNextId() string {
	if x != nil {
		return x.NextId
	}
	return ""
}

func (x *ListDNIReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListDNIResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VhfList [][]byte `protobuf:"bytes,1,rep,name=vhfList,proto3" json:"vhfList,omitempty"`
	NextId  string   `protobuf:"bytes,2,opt,name=nextId,proto3" json:"nextId,omitempty"`
}

func (x *ListDNIResp) Reset() {
	*x = ListDNIResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDNIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDNIResp) ProtoMessage() {}

func (x *ListDNIResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDNIResp.ProtoReflect.Descriptor instead.
func (*ListDNIResp) Descriptor() ([]byte, []int) {
	return file_msg_node_proto_rawDescGZIP(), []int{3}
}

func (x *ListDNIResp) GetVhfList() [][]byte {
	if x != nil {
		return x.VhfList
	}
	return nil
}

func (x *ListDNIResp) GetNextId() string {
	if x != nil {
		return x.NextId
	}
	return ""
}

var File_msg_node_proto protoreflect.FileDescriptor

var file_msg_node_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x70, 0x6b, 0x74, 0x22, 0x52, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x74,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x4e,
	0x49, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x4e, 0x49, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x68, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x07, 0x76, 0x68, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x65, 0x78, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x65, 0x78,
	0x74, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_node_proto_rawDescOnce sync.Once
	file_msg_node_proto_rawDescData = file_msg_node_proto_rawDesc
)

func file_msg_node_proto_rawDescGZIP() []byte {
	file_msg_node_proto_rawDescOnce.Do(func() {
		file_msg_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_node_proto_rawDescData)
	})
	return file_msg_node_proto_rawDescData
}

var file_msg_node_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_node_proto_goTypes = []interface{}{
	(*GetNodeCapacityReq)(nil),  // 0: pkt.GetNodeCapacityReq
	(*GetNodeCapacityResp)(nil), // 1: pkt.GetNodeCapacityResp
	(*ListDNIReq)(nil),          // 2: pkt.ListDNIReq
	(*ListDNIResp)(nil),         // 3: pkt.ListDNIResp
}
var file_msg_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_node_proto_init() }
func file_msg_node_proto_init() {
	if File_msg_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeCapacityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeCapacityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDNIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDNIResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_node_proto_goTypes,
		DependencyIndexes: file_msg_node_proto_depIdxs,
		MessageInfos:      file_msg_node_proto_msgTypes,
	}.Build()
	File_msg_node_proto = out.File
	file_msg_node_proto_rawDesc = nil
	file_msg_node_proto_goTypes = nil
	file_msg_node_proto_depIdxs = nil
}
