// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.21.2
// source: msg.bp.proto

package pkt

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ActiveCache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vnu *ActiveCache_VNU `protobuf:"group,1,opt,name=VNU,json=vnu" json:"vnu,omitempty"`
}

func (x *ActiveCache) Reset() {
	*x = ActiveCache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCache) ProtoMessage() {}

func (x *ActiveCache) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCache.ProtoReflect.Descriptor instead.
func (*ActiveCache) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{0}
}

func (x *ActiveCache) GetVnu() *ActiveCache_VNU {
	if x != nil {
		return x.Vnu
	}
	return nil
}

type GetBlockUsedSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []int64 `protobuf:"varint,1,rep,name=id" json:"id,omitempty"`
}

func (x *GetBlockUsedSpace) Reset() {
	*x = GetBlockUsedSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockUsedSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockUsedSpace) ProtoMessage() {}

func (x *GetBlockUsedSpace) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockUsedSpace.ProtoReflect.Descriptor instead.
func (*GetBlockUsedSpace) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockUsedSpace) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type NodeSyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node []*NodeSyncReq_Node `protobuf:"group,1,rep,name=Node,json=node" json:"node,omitempty"`
}

func (x *NodeSyncReq) Reset() {
	*x = NodeSyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSyncReq) ProtoMessage() {}

func (x *NodeSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSyncReq.ProtoReflect.Descriptor instead.
func (*NodeSyncReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSyncReq) GetNode() []*NodeSyncReq_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RelationShipSum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mowner    []string `protobuf:"bytes,1,rep,name=mowner" json:"mowner,omitempty"`
	Usedspace []uint64 `protobuf:"varint,2,rep,name=usedspace" json:"usedspace,omitempty"`
}

func (x *RelationShipSum) Reset() {
	*x = RelationShipSum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelationShipSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationShipSum) ProtoMessage() {}

func (x *RelationShipSum) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationShipSum.ProtoReflect.Descriptor instead.
func (*RelationShipSum) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{3}
}

func (x *RelationShipSum) GetMowner() []string {
	if x != nil {
		return x.Mowner
	}
	return nil
}

func (x *RelationShipSum) GetUsedspace() []uint64 {
	if x != nil {
		return x.Usedspace
	}
	return nil
}

type Relationship struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   *string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	MpoolOwner *string `protobuf:"bytes,2,opt,name=mpoolOwner" json:"mpoolOwner,omitempty"`
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{4}
}

func (x *Relationship) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Relationship) GetMpoolOwner() string {
	if x != nil && x.MpoolOwner != nil {
		return *x.MpoolOwner
	}
	return ""
}

type SaveObjectMetaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    *int32  `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	VNU       *string `protobuf:"bytes,2,opt,name=VNU" json:"VNU,omitempty"`
	Refer     []byte  `protobuf:"bytes,3,opt,name=Refer" json:"Refer,omitempty"`
	UsedSpace *uint64 `protobuf:"varint,4,opt,name=usedSpace" json:"usedSpace,omitempty"`
	Mode      *bool   `protobuf:"varint,5,opt,name=mode" json:"mode,omitempty"`
}

func (x *SaveObjectMetaReq) Reset() {
	*x = SaveObjectMetaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveObjectMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectMetaReq) ProtoMessage() {}

func (x *SaveObjectMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectMetaReq.ProtoReflect.Descriptor instead.
func (*SaveObjectMetaReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{5}
}

func (x *SaveObjectMetaReq) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *SaveObjectMetaReq) GetVNU() string {
	if x != nil && x.VNU != nil {
		return *x.VNU
	}
	return ""
}

func (x *SaveObjectMetaReq) GetRefer() []byte {
	if x != nil {
		return x.Refer
	}
	return nil
}

func (x *SaveObjectMetaReq) GetUsedSpace() uint64 {
	if x != nil && x.UsedSpace != nil {
		return *x.UsedSpace
	}
	return 0
}

func (x *SaveObjectMetaReq) GetMode() bool {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return false
}

type SaveObjectMetaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists *bool `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
}

func (x *SaveObjectMetaResp) Reset() {
	*x = SaveObjectMetaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveObjectMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveObjectMetaResp) ProtoMessage() {}

func (x *SaveObjectMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveObjectMetaResp.ProtoReflect.Descriptor instead.
func (*SaveObjectMetaResp) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{6}
}

func (x *SaveObjectMetaResp) GetExists() bool {
	if x != nil && x.Exists != nil {
		return *x.Exists
	}
	return false
}

type TotalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B *bool `protobuf:"varint,1,opt,name=b" json:"b,omitempty"`
}

func (x *TotalReq) Reset() {
	*x = TotalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalReq) ProtoMessage() {}

func (x *TotalReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalReq.ProtoReflect.Descriptor instead.
func (*TotalReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{7}
}

func (x *TotalReq) GetB() bool {
	if x != nil && x.B != nil {
		return *x.B
	}
	return false
}

type TotalResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileTotal     *uint64 `protobuf:"varint,1,opt,name=fileTotal" json:"fileTotal,omitempty"`
	SpaceTotal    *uint64 `protobuf:"varint,2,opt,name=spaceTotal" json:"spaceTotal,omitempty"`
	Usedspace     *uint64 `protobuf:"varint,3,opt,name=usedspace" json:"usedspace,omitempty"`
	BkTotal       *uint64 `protobuf:"varint,4,opt,name=bkTotal" json:"bkTotal,omitempty"`
	ActualBkTotal *uint64 `protobuf:"varint,5,opt,name=actualBkTotal" json:"actualBkTotal,omitempty"`
}

func (x *TotalResp) Reset() {
	*x = TotalResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalResp) ProtoMessage() {}

func (x *TotalResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalResp.ProtoReflect.Descriptor instead.
func (*TotalResp) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{8}
}

func (x *TotalResp) GetFileTotal() uint64 {
	if x != nil && x.FileTotal != nil {
		return *x.FileTotal
	}
	return 0
}

func (x *TotalResp) GetSpaceTotal() uint64 {
	if x != nil && x.SpaceTotal != nil {
		return *x.SpaceTotal
	}
	return 0
}

func (x *TotalResp) GetUsedspace() uint64 {
	if x != nil && x.Usedspace != nil {
		return *x.Usedspace
	}
	return 0
}

func (x *TotalResp) GetBkTotal() uint64 {
	if x != nil && x.BkTotal != nil {
		return *x.BkTotal
	}
	return 0
}

func (x *TotalResp) GetActualBkTotal() uint64 {
	if x != nil && x.ActualBkTotal != nil {
		return *x.ActualBkTotal
	}
	return 0
}

type UpdateDNIReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dni    []byte  `protobuf:"bytes,1,opt,name=dni" json:"dni,omitempty"`
	Nodeid *uint32 `protobuf:"varint,2,opt,name=nodeid" json:"nodeid,omitempty"`
	Delete *bool   `protobuf:"varint,3,opt,name=delete" json:"delete,omitempty"`
}

func (x *UpdateDNIReq) Reset() {
	*x = UpdateDNIReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDNIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDNIReq) ProtoMessage() {}

func (x *UpdateDNIReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDNIReq.ProtoReflect.Descriptor instead.
func (*UpdateDNIReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDNIReq) GetDni() []byte {
	if x != nil {
		return x.Dni
	}
	return nil
}

func (x *UpdateDNIReq) GetNodeid() uint32 {
	if x != nil && x.Nodeid != nil {
		return *x.Nodeid
	}
	return 0
}

func (x *UpdateDNIReq) GetDelete() bool {
	if x != nil && x.Delete != nil {
		return *x.Delete
	}
	return false
}

type UpdateDNIMutiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dni []*UpdateDNIMutiReq_DNI `protobuf:"group,1,rep,name=DNI,json=dni" json:"dni,omitempty"`
}

func (x *UpdateDNIMutiReq) Reset() {
	*x = UpdateDNIMutiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDNIMutiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDNIMutiReq) ProtoMessage() {}

func (x *UpdateDNIMutiReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDNIMutiReq.ProtoReflect.Descriptor instead.
func (*UpdateDNIMutiReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateDNIMutiReq) GetDni() []*UpdateDNIMutiReq_DNI {
	if x != nil {
		return x.Dni
	}
	return nil
}

type UserListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId *int32 `protobuf:"varint,1,opt,name=lastId" json:"lastId,omitempty"`
	Count  *int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (x *UserListReq) Reset() {
	*x = UserListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListReq) ProtoMessage() {}

func (x *UserListReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListReq.ProtoReflect.Descriptor instead.
func (*UserListReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{11}
}

func (x *UserListReq) GetLastId() int32 {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return 0
}

func (x *UserListReq) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type UserListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userspace []*UserListResp_UserSpace `protobuf:"group,1,rep,name=UserSpace,json=userspace" json:"userspace,omitempty"`
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{12}
}

func (x *UserListResp) GetUserspace() []*UserListResp_UserSpace {
	if x != nil {
		return x.Userspace
	}
	return nil
}

type UserSpaceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid *uint32 `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
}

func (x *UserSpaceReq) Reset() {
	*x = UserSpaceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSpaceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpaceReq) ProtoMessage() {}

func (x *UserSpaceReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpaceReq.ProtoReflect.Descriptor instead.
func (*UserSpaceReq) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{13}
}

func (x *UserSpaceReq) GetUserid() uint32 {
	if x != nil && x.Userid != nil {
		return *x.Userid
	}
	return 0
}

type UserSpaceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jsonstr *string `protobuf:"bytes,1,opt,name=jsonstr" json:"jsonstr,omitempty"`
}

func (x *UserSpaceResp) Reset() {
	*x = UserSpaceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSpaceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpaceResp) ProtoMessage() {}

func (x *UserSpaceResp) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpaceResp.ProtoReflect.Descriptor instead.
func (*UserSpaceResp) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{14}
}

func (x *UserSpaceResp) GetJsonstr() string {
	if x != nil && x.Jsonstr != nil {
		return *x.Jsonstr
	}
	return ""
}

type ActiveCache_VNU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp         *uint32 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	MachineIdentifier *int32  `protobuf:"varint,2,opt,name=machineIdentifier" json:"machineIdentifier,omitempty"`
	ProcessIdentifier *uint32 `protobuf:"varint,3,opt,name=processIdentifier" json:"processIdentifier,omitempty"`
	Counter           *int32  `protobuf:"varint,4,opt,name=counter" json:"counter,omitempty"`
}

func (x *ActiveCache_VNU) Reset() {
	*x = ActiveCache_VNU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveCache_VNU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCache_VNU) ProtoMessage() {}

func (x *ActiveCache_VNU) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCache_VNU.ProtoReflect.Descriptor instead.
func (*ActiveCache_VNU) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ActiveCache_VNU) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ActiveCache_VNU) GetMachineIdentifier() int32 {
	if x != nil && x.MachineIdentifier != nil {
		return *x.MachineIdentifier
	}
	return 0
}

func (x *ActiveCache_VNU) GetProcessIdentifier() uint32 {
	if x != nil && x.ProcessIdentifier != nil {
		return *x.ProcessIdentifier
	}
	return 0
}

func (x *ActiveCache_VNU) GetCounter() int32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return 0
}

type NodeSyncReq_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Cpu           *int32   `protobuf:"varint,2,opt,name=cpu" json:"cpu,omitempty"`
	Memory        *int32   `protobuf:"varint,3,opt,name=memory" json:"memory,omitempty"`
	Bandwidth     *int32   `protobuf:"varint,4,opt,name=bandwidth" json:"bandwidth,omitempty"`
	MaxDataSpace  *int64   `protobuf:"varint,5,opt,name=maxDataSpace" json:"maxDataSpace,omitempty"`
	AssignedSpace *int64   `protobuf:"varint,6,opt,name=assignedSpace" json:"assignedSpace,omitempty"`
	UsedSpace     *int64   `protobuf:"varint,7,opt,name=usedSpace" json:"usedSpace,omitempty"`
	Addrs         []string `protobuf:"bytes,8,rep,name=addrs" json:"addrs,omitempty"`
	Relay         *int32   `protobuf:"varint,9,opt,name=relay" json:"relay,omitempty"`
	Version       *int32   `protobuf:"varint,10,opt,name=version" json:"version,omitempty"`
	Rebuilding    *int32   `protobuf:"varint,11,opt,name=rebuilding" json:"rebuilding,omitempty"`
	RealSpace     *int64   `protobuf:"varint,12,opt,name=realSpace" json:"realSpace,omitempty"`
	Tx            *int64   `protobuf:"varint,13,opt,name=tx" json:"tx,omitempty"`
	Rx            *int64   `protobuf:"varint,14,opt,name=rx" json:"rx,omitempty"`
	Other         *string  `protobuf:"bytes,15,opt,name=other" json:"other,omitempty"`
	Timestamp     *int64   `protobuf:"varint,16,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (x *NodeSyncReq_Node) Reset() {
	*x = NodeSyncReq_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSyncReq_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSyncReq_Node) ProtoMessage() {}

func (x *NodeSyncReq_Node) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSyncReq_Node.ProtoReflect.Descriptor instead.
func (*NodeSyncReq_Node) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NodeSyncReq_Node) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NodeSyncReq_Node) GetCpu() int32 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *NodeSyncReq_Node) GetMemory() int32 {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return 0
}

func (x *NodeSyncReq_Node) GetBandwidth() int32 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

func (x *NodeSyncReq_Node) GetMaxDataSpace() int64 {
	if x != nil && x.MaxDataSpace != nil {
		return *x.MaxDataSpace
	}
	return 0
}

func (x *NodeSyncReq_Node) GetAssignedSpace() int64 {
	if x != nil && x.AssignedSpace != nil {
		return *x.AssignedSpace
	}
	return 0
}

func (x *NodeSyncReq_Node) GetUsedSpace() int64 {
	if x != nil && x.UsedSpace != nil {
		return *x.UsedSpace
	}
	return 0
}

func (x *NodeSyncReq_Node) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NodeSyncReq_Node) GetRelay() int32 {
	if x != nil && x.Relay != nil {
		return *x.Relay
	}
	return 0
}

func (x *NodeSyncReq_Node) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *NodeSyncReq_Node) GetRebuilding() int32 {
	if x != nil && x.Rebuilding != nil {
		return *x.Rebuilding
	}
	return 0
}

func (x *NodeSyncReq_Node) GetRealSpace() int64 {
	if x != nil && x.RealSpace != nil {
		return *x.RealSpace
	}
	return 0
}

func (x *NodeSyncReq_Node) GetTx() int64 {
	if x != nil && x.Tx != nil {
		return *x.Tx
	}
	return 0
}

func (x *NodeSyncReq_Node) GetRx() int64 {
	if x != nil && x.Rx != nil {
		return *x.Rx
	}
	return 0
}

func (x *NodeSyncReq_Node) GetOther() string {
	if x != nil && x.Other != nil {
		return *x.Other
	}
	return ""
}

func (x *NodeSyncReq_Node) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type UpdateDNIMutiReq_DNI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dni    []byte  `protobuf:"bytes,1,opt,name=dni" json:"dni,omitempty"`
	Nodeid *uint32 `protobuf:"varint,2,opt,name=nodeid" json:"nodeid,omitempty"`
	Delete *bool   `protobuf:"varint,3,opt,name=delete" json:"delete,omitempty"`
}

func (x *UpdateDNIMutiReq_DNI) Reset() {
	*x = UpdateDNIMutiReq_DNI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDNIMutiReq_DNI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDNIMutiReq_DNI) ProtoMessage() {}

func (x *UpdateDNIMutiReq_DNI) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDNIMutiReq_DNI.ProtoReflect.Descriptor instead.
func (*UpdateDNIMutiReq_DNI) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{10, 0}
}

func (x *UpdateDNIMutiReq_DNI) GetDni() []byte {
	if x != nil {
		return x.Dni
	}
	return nil
}

func (x *UpdateDNIMutiReq_DNI) GetNodeid() uint32 {
	if x != nil && x.Nodeid != nil {
		return *x.Nodeid
	}
	return 0
}

func (x *UpdateDNIMutiReq_DNI) GetDelete() bool {
	if x != nil && x.Delete != nil {
		return *x.Delete
	}
	return false
}

type UserListResp_UserSpace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     *uint32 `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	UserName   *string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	SpaceTotal *uint64 `protobuf:"varint,3,opt,name=spaceTotal" json:"spaceTotal,omitempty"`
}

func (x *UserListResp_UserSpace) Reset() {
	*x = UserListResp_UserSpace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bp_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserListResp_UserSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp_UserSpace) ProtoMessage() {}

func (x *UserListResp_UserSpace) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bp_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp_UserSpace.ProtoReflect.Descriptor instead.
func (*UserListResp_UserSpace) Descriptor() ([]byte, []int) {
	return file_msg_bp_proto_rawDescGZIP(), []int{12, 0}
}

func (x *UserListResp_UserSpace) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *UserListResp_UserSpace) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *UserListResp_UserSpace) GetSpaceTotal() uint64 {
	if x != nil && x.SpaceTotal != nil {
		return *x.SpaceTotal
	}
	return 0
}

var File_msg_bp_proto protoreflect.FileDescriptor

var file_msg_bp_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x70, 0x6b, 0x74, 0x22, 0xd1, 0x01, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x6e, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0a,
	0x32, 0x14, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x56, 0x4e, 0x55, 0x52, 0x03, 0x76, 0x6e, 0x75, 0x1a, 0x99, 0x01, 0x0a, 0x03,
	0x56, 0x4e, 0x55, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12,
	0x2c, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd9, 0x03, 0x0a,
	0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x15, 0x2e, 0x70, 0x6b, 0x74,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x1a, 0x9e, 0x03, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63,
	0x70, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61,
	0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x62,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x6d, 0x61, 0x78, 0x44, 0x61, 0x74, 0x61, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x74, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x78, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x72, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x47, 0x0a, 0x0f, 0x52, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x68, 0x69, 0x70, 0x53, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6d, 0x70, 0x6f, 0x6f, 0x6c, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x85, 0x01,
	0x0a, 0x11, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x56,
	0x4e, 0x55, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x56, 0x4e, 0x55, 0x12, 0x14, 0x0a,
	0x05, 0x52, 0x65, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x0c, 0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x62, 0x22, 0xa7, 0x01,
	0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x64, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x64, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6b, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x6b, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x42, 0x6b, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c,
	0x42, 0x6b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x50, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x4e, 0x49, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6e, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x6e, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x4e, 0x49, 0x4d, 0x75, 0x74, 0x69, 0x52, 0x65, 0x71, 0x12, 0x2b,
	0x0a, 0x03, 0x64, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x19, 0x2e, 0x70, 0x6b,
	0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x4e, 0x49, 0x4d, 0x75, 0x74, 0x69, 0x52,
	0x65, 0x71, 0x2e, 0x44, 0x4e, 0x49, 0x52, 0x03, 0x64, 0x6e, 0x69, 0x1a, 0x47, 0x0a, 0x03, 0x44,
	0x4e, 0x49, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x64, 0x6e, 0x69, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x1b, 0x2e, 0x70, 0x6b, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x5f, 0x0a,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x73, 0x70, 0x61, 0x63, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x26,
	0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x73, 0x74,
	0x72,
}

var (
	file_msg_bp_proto_rawDescOnce sync.Once
	file_msg_bp_proto_rawDescData = file_msg_bp_proto_rawDesc
)

func file_msg_bp_proto_rawDescGZIP() []byte {
	file_msg_bp_proto_rawDescOnce.Do(func() {
		file_msg_bp_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_bp_proto_rawDescData)
	})
	return file_msg_bp_proto_rawDescData
}

var file_msg_bp_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_msg_bp_proto_goTypes = []interface{}{
	(*ActiveCache)(nil),            // 0: pkt.ActiveCache
	(*GetBlockUsedSpace)(nil),      // 1: pkt.GetBlockUsedSpace
	(*NodeSyncReq)(nil),            // 2: pkt.NodeSyncReq
	(*RelationShipSum)(nil),        // 3: pkt.RelationShipSum
	(*Relationship)(nil),           // 4: pkt.Relationship
	(*SaveObjectMetaReq)(nil),      // 5: pkt.SaveObjectMetaReq
	(*SaveObjectMetaResp)(nil),     // 6: pkt.SaveObjectMetaResp
	(*TotalReq)(nil),               // 7: pkt.TotalReq
	(*TotalResp)(nil),              // 8: pkt.TotalResp
	(*UpdateDNIReq)(nil),           // 9: pkt.UpdateDNIReq
	(*UpdateDNIMutiReq)(nil),       // 10: pkt.UpdateDNIMutiReq
	(*UserListReq)(nil),            // 11: pkt.UserListReq
	(*UserListResp)(nil),           // 12: pkt.UserListResp
	(*UserSpaceReq)(nil),           // 13: pkt.UserSpaceReq
	(*UserSpaceResp)(nil),          // 14: pkt.UserSpaceResp
	(*ActiveCache_VNU)(nil),        // 15: pkt.ActiveCache.VNU
	(*NodeSyncReq_Node)(nil),       // 16: pkt.NodeSyncReq.Node
	(*UpdateDNIMutiReq_DNI)(nil),   // 17: pkt.UpdateDNIMutiReq.DNI
	(*UserListResp_UserSpace)(nil), // 18: pkt.UserListResp.UserSpace
}
var file_msg_bp_proto_depIdxs = []int32{
	15, // 0: pkt.ActiveCache.vnu:type_name -> pkt.ActiveCache.VNU
	16, // 1: pkt.NodeSyncReq.node:type_name -> pkt.NodeSyncReq.Node
	17, // 2: pkt.UpdateDNIMutiReq.dni:type_name -> pkt.UpdateDNIMutiReq.DNI
	18, // 3: pkt.UserListResp.userspace:type_name -> pkt.UserListResp.UserSpace
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_msg_bp_proto_init() }
func file_msg_bp_proto_init() {
	if File_msg_bp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_bp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveCache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockUsedSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelationShipSum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Relationship); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveObjectMetaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveObjectMetaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDNIReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDNIMutiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSpaceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSpaceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveCache_VNU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSyncReq_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDNIMutiReq_DNI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bp_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserListResp_UserSpace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_bp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_bp_proto_goTypes,
		DependencyIndexes: file_msg_bp_proto_depIdxs,
		MessageInfos:      file_msg_bp_proto_msgTypes,
	}.Build()
	File_msg_bp_proto = out.File
	file_msg_bp_proto_rawDesc = nil
	file_msg_bp_proto_goTypes = nil
	file_msg_bp_proto_depIdxs = nil
}
